services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=7770
    ports:
      - "7770:7770"

  proxy:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app